version: '3.9'

services:
  # üóÑÔ∏è Base de datos MySQL
  mysql:
    image: mysql:8
    container_name: digital-payment-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: digital_payment_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ptest"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # üåê Eureka Server
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    restart: always

  # üë§ Users Service
  users-service:
    build: ./users-service
    container_name: users-service
    depends_on:
      eureka-server:
        condition: service_started
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/digital_payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_APPLICATION_NAME: users-service
    restart: on-failure
    command: sh -c "sleep 10 && java -jar app.jar"

  # üí≥ Accounts Service
  accounts-service:
    build: ./accounts-service
    container_name: accounts-service
    depends_on:
      eureka-server:
        condition: service_started
      mysql:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/digital_payment_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_APPLICATION_NAME: accounts-service
    restart: on-failure
    command: sh -c "sleep 10 && java -jar app.jar"

  # üö™ API Gateway
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=gateway-service
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID=true
    networks:
      - digital-payment-network

networks:
  digital-payment-network:
    driver: bridge

volumes:
  mysql_data:
